services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped
    environment:
      - TZ=America/Bogota

  data-logger:
    build: ./logger
    container_name: data-logger
    volumes:
      - ./data:/data
      - ./logger:/app
    working_dir: /app
    command: python main.py
    depends_on:
      - mosquitto
    restart: unless-stopped
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - DB_PATH=/data/sensores.db
      - MQTT_CAMPOS_ESPERADOS=${MQTT_CAMPOS_ESPERADOS}

  gateway-ubidots:
    build: ./ubidots
    container_name: gateway-ubidots
    volumes:
      - ./data:/data
    working_dir: /app
    command: python gateway_ubidots_v3.py
    depends_on:
      - data-logger
    restart: unless-stopped
    environment:
      - UBIDOTS_TOKEN=${UBIDOTS_TOKEN}
      - DEVICE_LABEL=${DEVICE_LABEL}
      - DB_PATH=/data/sensores.db

  ia-analisis:
    build: ./ia
    container_name: ia-analisis
    volumes:
      - ./data:/data
    working_dir: /app
    command: python ia_analisisV2.py
    depends_on:
      - gateway-ubidots
    restart: unless-stopped
    environment:
      - UBIDOTS_TOKEN=${UBIDOTS_TOKEN}
      - DEVICE_LABEL=${DEVICE_LABEL}
      - DB_PATH=/data/sensores.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}

volumes:
  mosquitto_data:
